version: "3.4"
services:
  identityservice:
    container_name: identityservice
    image: docker.sprun.ir/identityservice:v2
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MehranPfx
    ports:
      - "10500:8080"
      - "10501:8081"
    volumes:
      - ./certs:/https:ro
      - ./Shared/Protos:/src/Shared/Protos:ro
      # - ./wwwroot/images:/src/wwwroot/images:rw
    networks:
      - identity-network
      - fms-backend-services_db
      - fms-backend-services_gw

networks:
  identity-network:
    external: true
  fms-backend-services_gw:
    external: true
  fms-backend-services_db:
    external: true