name: CI/CD Pipeline

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD_DEV }}" | docker login -u "${{ secrets.DOCKER_USERNAME_DEV }}" --password-stdin docker.sprun.ir
      - name: Build and Push
        run: |
          docker compose -f "docker-compose-dev.yml" -f "docker-compose.override.yml"  build
          docker compose -f "docker-compose-dev.yml" -f "docker-compose.override.yml"  push
  deploy:
    runs-on: ubuntu-latest
    needs: build
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_DEV }}
          username: ${{ secrets.SERVER_USER_DEV }}
          password: ${{ secrets.SERVER_PASSWORD_DEV }}
          # port: 3360
          script: |
            cd /home/aron/identityservice
            docker compose  -f "docker-compose-dev.yml" -f "docker-compose.override.yml"  pull
            docker compose  -f "docker-compose-dev.yml" -f "docker-compose.override.yml"  up -d

#docker-compose  -f "docker-compose.yml" -f "docker-compose.override.yml" build
#docker-compose  -f "docker-compose.yml" -f "docker-compose.override.yml" push
